export enum AppStatus {
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  NOT_SUBMITTED = 'NOT_SUBMITTED',
  RETURNED = 'RETURNED',
  EXPIRED = 'EXPIRED',
}
