import {
  CreateAgencyDto,
  CreateCompanyDto,
  CreateIndividualDto,
  CreateOperatorDto,
  UpdateAgencyDto,
  UpdateCompanyDto,
  UpdateIndividualDto,
  UpdateOperatorDto,
} from './dto';
import { CreateCommunityVendorDto } from './dto/community-vendor/create-community-vendor.dto';
import { UpdateCommunityVendorDto } from './dto/community-vendor/update-community-vendor.dto';
import { AccountTypeEnum } from './enums';

type Options = {
  fillable: string[];
  relations: string[];
  searchable: string[];
  createDto: any;
  updateDto: any;
};

export type AccountTypeMapping = Record<AccountTypeEnum, Options>;
export const accountTypeMapping: AccountTypeMapping = {
  [AccountTypeEnum.INDIVIDUAL]: {
    fillable: [
      'firstName',
      'lastName',
      'otherNames',
      'isExpatriate',
      'dob',
      'gender',
      'phoneNumber',
      'countryId',
      'nationalityId',
      'altEmail',
      'altPhoneNumber',
      'address',
      'stateId',
      'cityResidence',
      'stateResidenceForeign',
      'stateResidenceId',
      'lgaId',
      'homeTown',
      'employmentStatus',
      'currentEmployer',
      'dateEmployed',
      'ninNumber',
      'accountId',
      'uuid',
      'competencyId',
    ],
    relations: ['country', 'nationality', 'state', 'lga', 'stateResidence'],
    searchable: [
      'users.firstName',
      'users.lastName',
      'individual.firstName',
      'individual.lastName',
      'individual.phoneNumber',
      'individual.competencyId',
      'users.email',
    ],
    createDto: CreateIndividualDto,
    updateDto: UpdateIndividualDto,
  },
  [AccountTypeEnum.AGENCY]: {
    fillable: [
      'firstName',
      'lastName',
      'position',
      'workflowGroups',
      'phoneNumber',
      'accountId',
      'uuid',
    ],
    relations: [],
    searchable: [
      'users.firstName',
      'users.lastName',
      'agency.firstName',
      'agency.lastName',
      'users.email',
    ],
    createDto: CreateAgencyDto,
    updateDto: UpdateAgencyDto,
  },
  [AccountTypeEnum.COMPANY]: {
    fillable: [
      'name',
      'rcNumber',
      'isOffshore',
      'email',
      'phoneNumber',
      'otherPhoneNumbers',
      'address',
      'businessCategoryId',
      'otherPhoneNumbers',
      'dprNumber',
      'nseStatus',
      'nseRegNo',
      'incorporationDate',
      'totalCompanyShares',
      'taxNumber',
      'facilityLocation',
      'facility',
      'staffStrengthLocal',
      'staffStrengthForeign',
      'staffStrengthForeignCount',
      'staffStrengthNigeriaCount',
      'nigerianOwnershipPercent',
      'accountId',
      'uuid',
      'isExternal',
    ],
    relations: ['businessCategory'],
    searchable: [
      'company.name',
      'users.email',
      'company.phoneNumber',
      'company.rcNumber',
      'company.nogicNumber',
    ],
    createDto: CreateCompanyDto,
    updateDto: UpdateCompanyDto,
  },
  [AccountTypeEnum.OPERATOR]: {
    fillable: [
      'name',
      'email',
      'password',
      'rcNumber',
      'address',
      'businessCategoryId',
      'categoryId',
      'category',
      'phoneNumber',
      'businessCategory',
      'otherPhoneNumbers',
      'address',
      'businessCategoryId',
      'otherPhoneNumbers',
      'dprNumber',
      'nseStatus',
      'nseRegNo',
      'incorporationDate',
      'totalCompanyShares',
      'taxNumber',
      'facilityLocation',
      'facility',
      'staffStrengthLocal',
      'staffStrengthForeign',
      'staffStrengthForeignCount',
      'staffStrengthNigeriaCount',
      'nigerianOwnershipPercent',
      'accountId',
      'uuid',
    ],
    searchable: [
      'operator.name',
      'users.email',
      'operator.phoneNumber',
      'operator.rcNumber',
      'operator.nogicNumber',
    ],
    relations: ['category', 'businessCategory'],
    createDto: CreateOperatorDto,
    updateDto: UpdateOperatorDto,
  },
  [AccountTypeEnum.COMMUNITY_VENDOR]: {
    fillable: [
      'name',
      'email',
      'address',
      'phoneNumber',
      'accountId',
      'stateId',
      'nogicNumber',
    ],
    relations: ['state'],
    searchable: ['communityVendor.name', 'communityVendor.nogicNumber'],
    createDto: CreateCommunityVendorDto,
    updateDto: UpdateCommunityVendorDto,
  },
};
